import { ArrowRight, Fingerprint, Layers3, Map, Workflow } from "lucide-react";
import { EmptyEvidence, PlaceholderBadge, SectionHeading } from "@/components/ui";
import { type ExpertSection } from "@/lib/scenes";

const evidence = [
  { id: "spatial" as const, icon: Map, stage: "STAGE 2", title: "Spatial risk", description: "Scene-relative moisture-risk evidence", detail: "Vegetation mask, spatial distribution, and relative risk classes." },
  { id: "temporal" as const, icon: Fingerprint, stage: "STAGE 3", title: "Temporal evidence", description: "Context across Sentinel-2 observations", detail: "Observation sequence, coverage, descriptive trends, and baseline context." },
  { id: "fusion" as const, icon: Workflow, stage: "STAGE 4", title: "Decision fusion", description: "A transparent path through the evidence", detail: "Evidence states, decision cutoff, rule trace, and ground-verification status." },
  { id: "spectral" as const, icon: Layers3, stage: "STAGE 4.5", title: "Hyperspectral value", description: "Fine structure beyond a compact baseline", detail: "Spectral signatures, group differences, and information-content comparison." },
];

export function ExpertShell({ view, onView }: { view: ExpertSection; onView: (view: ExpertSection) => void }) {
  if (view === "methodology") return <Methodology />;
  if (view === "provenance") return <Provenance />;
  const active = evidence.find((item) => item.id === view);
  if (active) return <><SectionHeading eyebrow={`${active.stage} / Expert workspace`} title={active.title} description={active.description} /><section className="panel analytical-panel"><div className="panel-header"><div><p className="eyebrow">Evidence area</p><h2>{active.id === "spectral" ? "Spectral signatures & comparison" : active.id === "temporal" ? "Observation timeline" : active.id === "fusion" ? "Evidence-to-decision trace" : "Scene-relative risk distribution"}</h2></div><PlaceholderBadge /></div><EmptyEvidence title="Evidence will appear here" description={active.detail} spatial={active.id === "spatial"} /></section><div className="expert-detail-grid"><section className="panel text-panel"><p className="eyebrow">Prepared for this view</p><h2>{active.id === "spatial" ? "Risk evidence & exclusions" : active.id === "temporal" ? "Trends & observation coverage" : active.id === "fusion" ? "Rule logic & verification" : "Signatures & spectral context"}</h2><p>{active.detail} These areas are placeholders; no values are displayed.</p><PlaceholderBadge /></section><section className="panel text-panel"><p className="eyebrow">Interpret with care</p><h2>{active.id === "spatial" ? "Relative does not mean absolute." : active.id === "temporal" ? "A trend does not establish a cause." : active.id === "fusion" ? "A decision still needs human review." : "More bands are not proof of accuracy."}</h2><p>{active.id === "spatial" ? "Scene-relative ranks are neither drought probabilities nor calibrated stress prevalence." : active.id === "temporal" ? "Clouds, phenology, harvest, and changing observation coverage can affect apparent trends." : active.id === "fusion" ? "Satellite agreement does not replace field verification. Automatic irrigation is unavailable." : "Spectral separation is exploratory and may reflect crop, soil, canopy, or atmospheric differences."}</p><button className="text-button" onClick={() => onView("methodology")}>Read the limitations <ArrowRight size={14} /></button></section></div></>;
  return <><SectionHeading eyebrow="Expert workspace" title="Trace the evidence." description="Spectral detail, temporal context, and a transparent path toward field verification." /><div className="expert-overview-grid">{evidence.map(({ id, icon: Icon, stage, title, description }) => <button className="evidence-module" key={id} onClick={() => onView(id)}><div className="module-top"><Icon size={21} strokeWidth={1.4} /><span className="mono">{stage}</span></div><h2>{title}</h2><p>{description}</p><div className="module-empty"><span />Evidence not connected</div><div className="module-bottom"><PlaceholderBadge /><ArrowRight size={17} /></div></button>)}</div><section className="evidence-chain panel"><div className="panel-header"><div><p className="eyebrow">The decision pathway</p><h2>Context before conclusion.</h2></div><PlaceholderBadge /></div><div className="chain-steps">{["Spectral evidence", "Temporal context", "Ground verification", "Human review"].map((label, i) => <div key={label}><span className="mono">0{i + 1}</span><strong>{label}</strong><small>{i === 2 ? "Future verification" : "Not connected"}</small>{i < 3 && <ArrowRight size={16} />}</div>)}</div></section><div className="expert-bottom-links"><button className="text-button" onClick={() => onView("methodology")}>Methodology & limitations <ArrowRight size={15} /></button><button className="text-button" onClick={() => onView("provenance")}>Data provenance <ArrowRight size={15} /></button></div></>;
}

function Methodology() {
  return <><SectionHeading eyebrow="Scientific context" title="Know the limits of the signal." description="The interpretation principles that guide AgriPulse-813. No scene results are displayed here." /><div className="methodology-list">{[
    ["Relative evidence", "Scene-relative moisture-risk ranks prioritize areas for verification. They are not calibrated drought probabilities, diagnoses, or irrigation prescriptions."],
    ["Time and context", "Sentinel-2 adds temporal context. Phenology, harvest, vegetation coverage, and observation quality can influence the signal. A short baseline is not a climatology."],
    ["Ground verification", "Satellite evidence cannot establish ground truth alone. Site-relevant, quality-checked field observations are needed before interpreting a cause or considering intervention."],
    ["Hyperspectral interpretation", "Fine spectral structure preserves information beyond a compact index baseline. Group differences do not independently validate water stress or establish improved detection accuracy."],
    ["Human responsibility", "AgriPulse supports evidence review. Automatic irrigation and control systems are outside this demo."],
  ].map(([title, text], index) => <section key={title}><span className="mono">0{index + 1}</span><h2>{title}</h2><p>{text}</p></section>)}</div><p className="methodology-footnote">These principles summarize the repository methodology. Detailed formulas, provenance, and result-specific limitations remain for the data integration stage.</p></>;
}

function Provenance() {
  return <><SectionHeading eyebrow="Source context" title="Keep the origin in view." description="A place for traceable inputs, processing context, and evidence integrity." /><section className="panel provenance-context"><p className="eyebrow gold-text">Current validated demo scene</p><h2>Konya, Turkey</h2><p>The processed demo scene is in Turkey. Syria and the Arab region are the intended deployment context; they do not have validated analysis in this demo.</p></section><div className="provenance-table" role="table" aria-label="Data source context"><div className="provenance-row provenance-head" role="row"><span role="columnheader">Source</span><span role="columnheader">Role</span><span role="columnheader">Preview status</span></div>{[["Planet Tanager", "Hyperspectral observations"], ["Sentinel-2", "Temporal observations"], ["Ground observations", "Future local verification"]].map(([source, role]) => <div className="provenance-row" role="row" key={source}><strong role="cell">{source}</strong><span role="cell">{role}</span><span role="cell">Not connected</span></div>)}</div><section className="panel text-panel provenance-placeholder"><div><p className="eyebrow">Provenance records</p><h2>Source records will appear here.</h2><p>Acquisition times, scene identifiers, processing versions, quality masks, and input checksums are reserved for connected evidence.</p></div><PlaceholderBadge /></section></>;
}
